name: CICD on PR
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.1]
    name: Setup, test & lint ${{ matrix.node-version }}
    steps:
      - name: Extract pr name
      - id: branch_name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo pr$(jq --raw-output .number "$GITHUB_EVENT_PATH"))"
      - name: print pr name
        shell: bash
        run: echo "/${{secrets.SERVICE_NAME}}-$BRANCH_NAME-${{secrets.SERVICE_NAME_FUNCTION}}"
  test1:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.1]
    name: Setup, test & lint ${{ matrix.node-version }}
    steps:
      - name: print pr name
        shell: bash
        run: echo ${{ BRANCH_NAME }}
