name: CICD on PR
on:
  - pull_request
jobs:
  set_var:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.1]
    outputs:
      BRANCH_NAME: ${{ steps.step1.outputs.BRANCH_NAME }}
      BASE_PATH: ${{ steps.step2.outputs.BASE_PATH }}
    steps:
      - id: step1
        run: echo "::set-output name=BRANCH_NAME::$(echo pr$(jq --raw-output .number "$GITHUB_EVENT_PATH"))"
      - id: step2
        run: echo "::set-output name=BASE_PATH::'/${{secrets.SERVICE_NAME}}-${{ steps.step1.outputs.BRANCH_NAME }}-${{secrets.SERVICE_NAME_FUNCTION}}'"
  job2:
    runs-on: ubuntu-latest
    needs: set_var
    steps:
      - run: echo ${{needs.set_var.outputs.BRANCH_NAME}} ${{ needs.steps.set_var.outputs.BASE_PATH }}
