name: CICD on PR
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.1]
    name: Setup, test & lint ${{ matrix.node-version }}
    steps:
      - name: Set tag var
        id: vars
        run: echo ::output name=BRANCH_NAME::$(echo pr$(jq --raw-output .number "$GITHUB_EVENT_PATH"))
      - name: Test arch var
        run: echo "Testing ${{ steps.vars.outputs.BRANCH_NAME }}"
      - name: print pr name
        shell: bash
        run: |
          echo "/${{secrets.SERVICE_NAME}}-${{ steps.vars.outputs.BRANCH_NAME }}-${{secrets.SERVICE_NAME_FUNCTION}}"
  test1:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.1]
    name: Setup, test & lint ${{ matrix.node-version }}
    steps:
      - name: print pr name
        shell: bash
        run: |
          echo "/${{secrets.SERVICE_NAME}}-${{ test.steps.vars.outputs.BRANCH_NAME }}-${{secrets.SERVICE_NAME_FUNCTION}}"
