name: CICD on PR
on:
  - pull_request
jobs:
  set_var:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.1]
    outputs:
      BRANCH_NAME: ${{ steps.step1.outputs.BRANCH_NAME }}
      BASE_PATH: ${{ steps.step2.outputs.BASE_PATH }}
      output2: ${{ steps.step3.outputs.test }}

    steps:
      - id: step1
        run: echo "::set-output name=BRANCH_NAME::$(echo pr$(jq --raw-output .number "$GITHUB_EVENT_PATH"))"
      - id: step2
        run: echo "::set-output name=BASE_PATH::/${{ steps.step1.outputs.BRANCH_NAME }}"
      - id: step3
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: set_var
    steps:
      - run: echo ${{needs.set_var.outputs.BRANCH_NAME}} ${{ needs.steps.set_var.outputs.BASE_PATH }} ${{needs.job1.outputs.output2}}
