name: CICD on PR
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.1]
    outputs:
      branch_name: ${{ steps.step1.outputs.BRANCH_NAME }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=BRANCH_NAME::$(echo pr$(jq --raw-output .number "$GITHUB_EVENT_PATH"))"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.branch_name}} ${{needs.job1.outputs.output2}}
